
language: r
sudo: required

r_packages:
  -  Matrix
  -  RColorBrewer
  -  caret
  -  dplyr
  -  e1071
  -  ggplot2
  -  ggrepel
  -  gplots
  -  plyr
  -  pROC
  -  readr
  -  scales
  -  stringr
  -  tibble
warnings_are_errors: false
